const familyData = [
  {
    id: 1,
    name: "Kunjabdulla",
    age: 0,
    gender: "male",
    parentIds: [],
    spouseId: 2,
  },
  {
    id: 2,
    name: "Aysha",
    age: 0,
    gender: "female",
    parentIds: [],
    spouseId: 1,
  },
  {
    id: 3,
    name: "Biyyathu",
    age: 0,
    gender: "female",
    parentIds: [1, 2],
    spouseId: 4,
  },
  {
    id: 4,
    name: "Yousuf",
    age: 0,
    gender: "male",
    parentIds: [],
    spouseId: 3,
  },
  {
    id: 5,
    name: "Sumayya",
    age: 0,
    gender: "female",
    parentIds: [3, 4],
    spouseId: null,
  },
  {
    id: 6,
    name: "Saheed",
    age: 0,
    gender: "male",
    parentIds: [3, 4],
    spouseId: null,
  },
  {
    id: 7,
    name: "Sinas",
    age: 0,
    gender: "male",
    parentIds: [3, 4],
    spouseId: null,
  },
  {
    id: 8,
    name: "Jameela",
    age: 0,
    gender: "female",
    parentIds: [1, 2],
    spouseId: 9,
  },
  {
    id: 9,
    name: "Hassan",
    age: 0,
    gender: "male",
    parentIds: [],
    spouseId: 8,
  },
  {
    id: 10,
    name: "Muhammed",
    age: 0,
    gender: "male",
    parentIds: [8, 9],
    spouseId: null,
  },
  {
    id: 11,
    name: "Uvais",
    age: 0,
    gender: "male",
    parentIds: [8, 9],
    spouseId: null,
  },
  {
    id: 12,
    name: "Aysha",
    age: 0,
    gender: "female",
    parentIds: [8, 9],
    spouseId: null,
  },
  {
    id: 13,
    name: "Azeez",
    age: 0,
    gender: "male",
    parentIds: [1, 2],
    spouseId: 14,
  },
  {
    id: 14,
    name: "Sameera",
    age: 0,
    gender: "female",
    parentIds: [],
    spouseId: 13,
  },
  {
    id: 15,
    name: "Thanseeha",
    age: 0,
    gender: "female",
    parentIds: [13, 14],
    spouseId: null,
  },
  {
    id: 16,
    name: "Adil",
    age: 0,
    gender: "male",
    parentIds: [13, 14],
    spouseId: null,
  },
  {
    id: 17,
    name: "Athika",
    age: 0,
    gender: "female",
    parentIds: [13, 14],
    spouseId: null,
  },
  {
    id: 18,
    name: "Ramla",
    age: 0,
    gender: "female",
    parentIds: [1, 2],
    spouseId: 19,
  },
  {
    id: 19,
    name: "Razak",
    age: 0,
    gender: "male",
    parentIds: [],
    spouseId: 18,
  },
  {
    id: 20,
    name: "Razeen",
    age: 0,
    gender: "male",
    parentIds: [18, 19],
    spouseId: null,
  },
  {
    id: 21,
    name: "Ramees",
    age: 0,
    gender: "male",
    parentIds: [18, 19],
    spouseId: null,
  },
  {
    id: 22,
    name: "Raniya",
    age: 0,
    gender: "female",
    parentIds: [18, 19],
    spouseId: null,
  },
  {
    id: 23,
    name: "Safiya",
    age: 0,
    gender: "female",
    parentIds: [1, 2],
    spouseId: 24,
  },
  {
    id: 24,
    name: "Muhammed",
    age: 0,
    gender: "male",
    parentIds: [],
    spouseId: 23,
  },
  {
    id: 25,
    name: "Fazil",
    age: 0,
    gender: "male",
    parentIds: [23, 24],
    spouseId: null,
  },
  {
    id: 26,
    name: "Fajisa",
    age: 0,
    gender: "female",
    parentIds: [23, 24],
    spouseId: null,
  },
  {
    id: 27,
    name: "Fadil",
    age: 0,
    gender: "male",
    parentIds: [23, 24],
    spouseId: null,
  },
  {
    id: 28,
    name: "Fanhas",
    age: 0,
    gender: "male",
    parentIds: [23, 24],
    spouseId: null,
  },
  {
    id: 29,
    name: "Muhammed",
    age: 0,
    gender: "male",
    parentIds: [1, 2],
    spouseId: 30,
  },
  {
    id: 30,
    name: "Fazeela",
    age: 0,
    gender: "female",
    parentIds: [],
    spouseId: 29,
  },
  {
    id: 31,
    name: "Ayan",
    age: 0,
    gender: "male",
    parentIds: [29, 30],
    spouseId: null,
  },
  {
    id: 32,
    name: "Nahyan",
    age: 0,
    gender: "male",
    parentIds: [29, 30],
    spouseId: null,
  },
  {
    id: 33,
    name: "Sameera",
    age: 0,
    gender: "female",
    parentIds: [1, 2],
    spouseId: 34,
  },
  {
    id: 34,
    name: "Ashraf",
    age: 0,
    gender: "male",
    parentIds: [],
    spouseId: 33,
  },
  {
    id: 35,
    name: "Ashil",
    age: 0,
    gender: "male",
    parentIds: [33, 34],
    spouseId: null,
  },
  {
    id: 36,
    name: "Amna",
    age: 0,
    gender: "female",
    parentIds: [33, 34],
    spouseId: null,
  },
  {
    id: 37,
    name: "Aizan",
    age: 0,
    gender: "male",
    parentIds: [33, 34],
    spouseId: null,
  },
  {
    id: 38,
    name: "Moidu",
    age: 0,
    gender: "male",
    parentIds: [1, 2],
    spouseId: 39,
  },
  {
    id: 39,
    name: "Asmina",
    age: 0,
    gender: "female",
    parentIds: [],
    spouseId: 38,
  },
  {
    id: 40,
    name: "Aman",
    age: 0,
    gender: "male",
    parentIds: [38, 39],
    spouseId: null,
  },
  {
    id: 41,
    name: "Aiman",
    age: 0,
    gender: "male",
    parentIds: [38, 39],
    spouseId: null,
  },
  {
    id: 42,
    name: "Marwa",
    age: 0,
    gender: "female",
    parentIds: [38, 39],
    spouseId: null,
  },
]

export default familyData
